databases:
  - name: todo-list-db
    databaseName: todolist
    user: todolist
    plan: free
    region: frankfurt

services:
  - type: web
    name: todo-list
    runtime: docker
    plan: free
    region: frankfurt
    branch: master
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: APP_NAME
        value: TodoList
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: true
      - key: APP_URL
        value: https://todo-list.onrender.com
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: debug
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: todo-list-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: todo-list-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: todo-list-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: todo-list-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: todo-list-db
          property: password
      - key: SESSION_DRIVER
        value: database
      - key: SESSION_LIFETIME
        value: 120
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: sync
      - key: BROADCAST_CONNECTION
        value: log
      - key: FILESYSTEM_DISK
        value: local
      - key: MAIL_MAILER
        value: log
